data:
  x_train_path: pathx
  y_train_path: pathy
  x_test_path: None
  y_test_path: None
  lengths_train_path: None
  lengths_test_path: None

model:
  type: LSTMClassifier
  pooling: None
  input_size: 6
  num_times: 140
  T: 25.1328
  skipt: 0.0
  hidden_size: 128
  num_rnn_layers: 3
  num_lin_layers_before: 3
  num_lin_layers_after: 3
  num_conv_layers: 3
  conv_size: 128
  output_size: 1
  normalise: 1

training:
  batch_size: 16
  num_epochs: 10
  learning_rate: 0.001
  gamma: 0.7

